export APPDYNAMICS_AGENT_ACCOUNT_NAME=
export APPDYNAMICS_GLOBAL_ACCOUNT_NAME=
export APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=
export APPDYNAMICS_CONTROLLER_HOST_NAME=
export APPDYNAMICS_SERVERLESS_API_ENDPOINT=https://pdx-sls-agent-api.saas.appdynamics.com
export APPDYNAMICS_CONTROLLER_PORT=443
export APPDYNAMICS_CONTROLLER_SSL_ENABLED="true"
export APPDYNAMICS_MACHINE_AGENT_ZIP_FILE="machineagent-bundle-64bit-linux-4.5.18.2430.zip"
